### ISSUE TITLE
Dead pending refresh is blocking other refreshes

### ISSUE THREAD

**Issue by felbecker** [KoBeWi/Godot-Action-Icon#4]
I think it's currently possible to lock the ActionIcon in an unfreshable state that will ignore all `refresh()` calls while waiting for a dead `_pending_refresh`. This happens if refresh is called while `is_visible_in_tree()` is false. In this case `_refresh()` will return and never set `_pending_refresh = false`. 

I don't know the implementation details. Is the check `not is_visible_in_tree()` in `_refresh()` actually needed? If yes, we could probably just move `_pending_refresh = false` before the if.

**Comment by KoBeWi** [comment]
`NOTIFICATION_VISIBILITY_CHANGED` is triggered when the icon enters scene tree (because it technically changes visibility), so the method is called again. There is no reason to refresh outside scene tree, because nothing is being displayed anyway.

**Comment by felbecker** [comment]
In my case, I have a dynamic ActionIcon that I drop into the scene wherever I need it. It looks like `refresh()` was implicitly called by setting a new `action_name` before adding the icon to the scene tree, expecting to see the correct icon after adding. 

`NOTIFICATION_VISIBILITY_CHANGED` triggers `refresh` but not `_refresh`. Since the former is already locked when adding to the tree, the issue remains. 

I do think it makes sense to modify the Icon outside the tree. Something like 
```
icon.action_name = "left"
add_child(icon)
```
and 
```
add_child(icon)
icon.action_name = "left"
```
should be equivalent.

**Comment by KoBeWi** [comment]
Yeah I just pushed a commit that makes `NOTIFICATION_VISIBILITY_CHANGED` call `_refresh()`. I think it fixes the issue?

**Comment by felbecker** [comment]
Yes, fixed. Thanks!
