### ISSUE TITLE
event.keycode always returning 0

### ISSUE THREAD

**Issue by sili3011** [KoBeWi/Godot-Action-Icon#5]
https://github.com/KoBeWi/Godot-Action-Icon/blob/99cbbd71964e2632d3a71c03e27631417371ddf8/addons/ActionIcon/ActionIcon.gd#L138

Had to replace `event.keycode` with `event.physical_keycode` for it to work, as the first option always returned 0.
My version:  v4.0.stable.mono.official [92bee43ad]

Might be a OS problem as mentionied [here](https://github.com/godotengine/godot/issues/56544)?

**Comment by KoBeWi** [comment]
The issue you linked is unrelated.
At some point InputMap editor was changed to default to physical keys, which use a different property. I fixed it in 6b43c1a2ab50a887d4dea781f556e1dc58d8a3ad
Thanks for reporting.
