### ISSUE TITLE
Invalid Resource ID

### ISSUE THREAD

**Issue by ghost** [KoBeWi/Godot-Action-Icon#7]
History: No errors at all on 1.3b

Error Text: W 0:00:04:0954   load: res://Scenes/Menu.tscn:12 - ext_resource, invalid UID: uid://di0tbwx1rdcw0 - using text path instead: res://addons/ActionIcon/Keyboard/Blank.png
  <C++ Source>   scene/resources/resource_format_text.cpp:447 @ load()

ActionIcon: 1.4
Godot: 4.1.2
OS: MacOS Sonoma 14.0

**Comment by KoBeWi** [comment]
For some reason I did not push .import files for the icons, so every time you upgrade the plugin by removing the folder and re-adding, the UIDs will change. I will fix this, but you'll need to open and re-save all scenes using ActionIcon. Sorry for the inconvenience.

**Comment by KoBeWi** [comment]
Fixed by 2c4467d5f1a2f75d33e1152ea9b8c592d4c49dcc
You'll need to do what I said above to fix the warnings and then it shouldn't happen anymore.

Also with 450ef60ca0b3d4f98d71b4e0196017bdc4d3465d if you upgrade to Godot 4.2 the textures dependencies will be removed altogether.
