### ISSUE TITLE
Fit Mode is not properly applied when opening a project

### ISSUE THREAD

**Issue by Eligiuss** [KoBeWi/Godot-Action-Icon#8]
ActionIcon version: 1.5
Godot version: 4.2 stable

I'm encountering an issue where the Fit mode property is seemingly not applied when opening a project.
Example with an action icon and a label:
![1](https://github.com/KoBeWi/Godot-Action-Icon/assets/6916662/24f34d9f-0bcc-40a2-bd75-0da9b945a72e)
What my scene looks like before I close my project, fit mode is set to "Match Width"

![2](https://github.com/KoBeWi/Godot-Action-Icon/assets/6916662/d427222a-8383-4cc7-9cab-62e876fb6202)
What it looks like when opening the project again

Setting fit mode to "Match Height" and then back again to "Match Width" makes it look like the first image again.

**Comment by KoBeWi** [comment]
Sorry, I had it on my TODO list for some time, but forgot to push it.
Fixed in 44a51c8ead8edd29d92bc101b590b45fd51543d9
